version: "3.7"

services:
  backend:
    image: ${IMAGE_NAME}
    container_name: ${PROJECT_NAME}_backend
    environment:
      - SITE_NAME=${SITE_NAME}
      - INSTALL_APPS=${INSTALL_APPS}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${PROJECT_NAME}_sites:/home/frappe/frappe-bench/sites
      - ${PROJECT_NAME}_logs:/home/frappe/frappe-bench/logs
    networks:
      - ${PROJECT_NAME}_network
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: ${PROJECT_NAME}_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${PROJECT_NAME}_db_data:/var/lib/mysql
    networks:
      - ${PROJECT_NAME}_network

  redis-cache:
    image: redis:alpine
    container_name: ${PROJECT_NAME}_redis_cache
    networks:
      - ${PROJECT_NAME}_network

  redis-queue:
    image: redis:alpine
    container_name: ${PROJECT_NAME}_redis_queue
    networks:
      - ${PROJECT_NAME}_network

  redis-socketio:
    image: redis:alpine
    container_name: ${PROJECT_NAME}_redis_socketio
    networks:
      - ${PROJECT_NAME}_network

  queue-short:
    image: ${IMAGE_NAME}
    container_name: ${PROJECT_NAME}_queue_short
    command: bench worker --queue short
    volumes:
      - ${PROJECT_NAME}_sites:/home/frappe/frappe-bench/sites
      - ${PROJECT_NAME}_logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis-queue
      - backend
    networks:
      - ${PROJECT_NAME}_network

  queue-long:
    image: ${IMAGE_NAME}
    container_name: ${PROJECT_NAME}_queue_long
    command: bench worker --queue long
    volumes:
      - ${PROJECT_NAME}_sites:/home/frappe/frappe-bench/sites
      - ${PROJECT_NAME}_logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis-queue
      - backend
    networks:
      - ${PROJECT_NAME}_network

  queue-default:
    image: ${IMAGE_NAME}
    container_name: ${PROJECT_NAME}_queue_default
    command: bench worker --queue default
    volumes:
      - ${PROJECT_NAME}_sites:/home/frappe/frappe-bench/sites
      - ${PROJECT_NAME}_logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis-queue
      - backend
    networks:
      - ${PROJECT_NAME}_network

  socketio:
    image: ${IMAGE_NAME}
    container_name: ${PROJECT_NAME}_socketio
    command: node /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - ${PROJECT_NAME}_sites:/home/frappe/frappe-bench/sites
      - ${PROJECT_NAME}_logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis-socketio
    networks:
      - ${PROJECT_NAME}_network

  frontend:
    image: ${IMAGE_NAME}
    container_name: ${PROJECT_NAME}_frontend
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ${PROJECT_NAME}_sites:/home/frappe/frappe-bench/sites
      - ${PROJECT_NAME}_logs:/home/frappe/frappe-bench/logs
    depends_on:
      - backend
    networks:
      - ${PROJECT_NAME}_network

volumes:
  ${PROJECT_NAME}_sites:
  ${PROJECT_NAME}_logs:
  ${PROJECT_NAME}_db_data:

networks:
  ${PROJECT_NAME}_network:
